### ISSUE TITLE
add instruction on how I can help

### ISSUE THREAD

**Issue by mhoffma** [realgud/realgud-lldb#2]
what specific information do you need from the lldb side to make this work?

**Comment by rocky** [comment]
Hi -

Thanks for the offer to help out. This project needs some love. I went through a debugger with the most support (my own, of course), and compared with `lldb/init.el`.

Here is what I found...

But first some background. Currently this program works by reading output from some debugger and tracking information from that. So although beefing up support on the lldb side would benefit this project, it would also benefit other projects that work like this. A frontend for debuggers called [DDD](https://www.gnu.org/software/ddd/) which is long been unmaintained also worked/works this way. But it is not inconceivable there are other front ends. 

## breakpoints

When you set a breakpoint, usally there is a message that says something like "Breakpoint _number_ set", where _number_ is the number you'd use to:
- attach/delete a condition
- enable/disable the breakpoint
- delete the breakpoint

Right now when (in _gdb_ terms) "enabling" or "disabling" a breakpoint we don't have anything to track that message, probably because _lldb_ doesn't report status. Possibly the same is true for attaching and deleting a condition or deleting the breakpoint. These have hash keys:
- `"brkpt-del"`
- `"brkpt-enable"`
- `"brkpt-disable"`

which would be used in a line like:

```
(setf (gethash "brkpt-del" realgud:lldb-pat-hash) ...)
```

Compare with https://github.com/realgud/realgud/blob/master/realgud/debugger/trepan2/init.el#L69 expanding the variable that's given there. 

## until command

The doc string for `realgud:cmd-until` gives this: 

> Continue until the current line. In some cases this is really two commands - setting a temporary breakpoint on the line and continuing execution."

What's the corresponding _lldb_ command for this? The output when running the corresponding command would be added into `lldb/init.el` something like this: 

```
(setf (gethash "until" realgud:lldb-command-hash) ...)
```

## language backtrace

Inside _gdb_ and _lldb_ when you issue a `backtrace` command, we can parse that output. However often the underlying programming language gives a backtrace before a fatal error. In _lldb_ I imagine even though the front-end may be C or C++, _lldb_ backtraces on fatal errors may look the same since it is the same underlying runtime. If it is the case that such a backtrace looks different, capturing a regular expression for that would be helpful

This would be added like this:

```
(setf (gethash "lang-backtrace" realgud:lldb-pat-hash)  ... )
```

**Comment by rocky** [comment]
A bit of the above has been done.

**Comment by mhoffma** [comment]
My project needs changed and sorry but I haven't had any time to dig into
this.

**Comment by rocky** [comment]
np
